import type { UmlDiagramTypeConfig, UmlDiagramType } from "./types";

export const UML_DIAGRAM_TYPES: UmlDiagramTypeConfig[] = [
  {
    type: "uml-class",
    label: "Class Diagram",
    icon: "view_in_ar",
    category: "Structural",
    allowedElements: [
      "uml_Class",
      "uml_AbstractClass",
      "uml_Interface",
      "uml_DataType",
      "uml_Enumeration",
      "uml_PrimitiveType",
      "uml_Signal",
      "uml_Note",
    ],
    allowedRelations: [
      "uml_rel_Association",
      "uml_rel_DirectedAssociation",
      "uml_rel_Aggregation",
      "uml_rel_Composition",
      "uml_rel_Dependency",
      "uml_rel_Generalization",
      "uml_rel_Realization",
      "uml_rel_Usage",
      "uml_rel_Substitution",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-usecase",
    label: "Use Case Diagram",
    icon: "person",
    category: "Behavioral",
    allowedElements: ["uml_Actor", "uml_UseCase", "uml_Subject", "uml_Note"],
    allowedRelations: [
      "uml_rel_AssociationUC",
      "uml_rel_Include",
      "uml_rel_Extend",
      "uml_rel_Generalization",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "force",
  },
  {
    type: "uml-component",
    label: "Component Diagram",
    icon: "widgets",
    category: "Structural",
    allowedElements: [
      "uml_Component",
      "uml_Port",
      "uml_ProvidedInterface",
      "uml_RequiredInterface",
      "uml_Artifact",
      "uml_Interface",
      "uml_Note",
    ],
    allowedRelations: [
      "uml_rel_Association",
      "uml_rel_Dependency",
      "uml_rel_Realization",
      "uml_rel_ComponentRealization",
      "uml_rel_ProvidedInterfaceRel",
      "uml_rel_RequiredInterfaceRel",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-deployment",
    label: "Deployment Diagram",
    icon: "dns",
    category: "Structural",
    allowedElements: [
      "uml_Node",
      "uml_Device",
      "uml_ExecutionEnvironment",
      "uml_Artifact",
      "uml_Component",
      "uml_DeploymentSpec",
      "uml_Note",
    ],
    allowedRelations: [
      "uml_rel_Association",
      "uml_rel_Dependency",
      "uml_rel_Deployment",
      "uml_rel_Manifestation",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-package",
    label: "Package Diagram",
    icon: "folder_open",
    category: "Structural",
    allowedElements: [
      "uml_Package",
      "uml_Model",
      "uml_Profile",
      "uml_Stereotype",
      "uml_Class",
      "uml_Interface",
      "uml_Note",
    ],
    allowedRelations: [
      "uml_rel_PackageImport",
      "uml_rel_PackageMerge",
      "uml_rel_ElementImport",
      "uml_rel_Dependency",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-activity",
    label: "Activity Diagram",
    icon: "account_tree",
    category: "Behavioral",
    allowedElements: [
      "uml_Activity",
      "uml_Action",
      "uml_CallBehaviorAction",
      "uml_SendSignalAction",
      "uml_AcceptEventAction",
      "uml_InitialNode",
      "uml_ActivityFinalNode",
      "uml_FlowFinalNode",
      "uml_DecisionNode",
      "uml_ForkJoinNode",
      "uml_ActivityPartition",
      "uml_ObjectNode",
      "uml_CentralBuffer",
      "uml_DataStoreNode",
      "uml_Note",
    ],
    allowedRelations: ["uml_rel_ControlFlow", "uml_rel_ObjectFlow", "uml_rel_NoteLink"],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-statemachine",
    label: "State Machine Diagram",
    icon: "crop_square",
    category: "Behavioral",
    allowedElements: [
      "uml_State",
      "uml_CompositeState",
      "uml_SubmachineState",
      "uml_PseudostateInitial",
      "uml_PseudostateFinal",
      "uml_PseudostateChoice",
      "uml_PseudostateJunction",
      "uml_PseudostateFork",
      "uml_PseudostateJoin",
      "uml_PseudostateShallowHistory",
      "uml_PseudostateDeepHistory",
      "uml_PseudostateEntryPoint",
      "uml_PseudostateExitPoint",
      "uml_Note",
    ],
    allowedRelations: ["uml_rel_Transition", "uml_rel_NoteLink"],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-sequence",
    label: "Sequence Diagram",
    icon: "swap_vert",
    category: "Interaction",
    allowedElements: [
      "uml_Lifeline",
      "uml_CombinedFragment",
      "uml_InteractionOperand",
      "uml_ExecutionSpecification",
      "uml_Note",
    ],
    allowedRelations: [
      "uml_rel_MessageSync",
      "uml_rel_MessageAsync",
      "uml_rel_MessageReturn",
      "uml_rel_MessageCreate",
      "uml_rel_MessageDestroy",
      "uml_rel_SelfMessage",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-object",
    label: "Object Diagram",
    icon: "data_object",
    category: "Structural",
    allowedElements: ["uml_Object", "uml_Note"],
    allowedRelations: ["uml_rel_Association", "uml_rel_NoteLink"],
    elkAlgorithm: "force",
  },
  {
    type: "uml-composite",
    label: "Composite Structure Diagram",
    icon: "grid_view",
    category: "Structural",
    allowedElements: ["uml_Class", "uml_Component", "uml_Port", "uml_Note"],
    allowedRelations: [
      "uml_rel_Association",
      "uml_rel_Dependency",
      "uml_rel_Generalization",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-profile",
    label: "Profile Diagram",
    icon: "tune",
    category: "Structural",
    allowedElements: ["uml_Profile", "uml_Stereotype", "uml_Class", "uml_Note"],
    allowedRelations: [
      "uml_rel_Generalization",
      "uml_rel_Dependency",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-communication",
    label: "Communication Diagram",
    icon: "share",
    category: "Interaction",
    allowedElements: ["uml_Lifeline", "uml_Note"],
    allowedRelations: [
      "uml_rel_Association",
      "uml_rel_MessageSync",
      "uml_rel_MessageAsync",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "force",
  },
  {
    type: "uml-timing",
    label: "Timing Diagram",
    icon: "timeline",
    category: "Interaction",
    allowedElements: ["uml_Lifeline", "uml_State", "uml_Note"],
    allowedRelations: [
      "uml_rel_MessageSync",
      "uml_rel_MessageAsync",
      "uml_rel_NoteLink",
    ],
    elkAlgorithm: "layered",
  },
  {
    type: "uml-interaction-overview",
    label: "Interaction Overview Diagram",
    icon: "account_tree",
    category: "Interaction",
    allowedElements: [
      "uml_Activity",
      "uml_Action",
      "uml_InitialNode",
      "uml_ActivityFinalNode",
      "uml_DecisionNode",
      "uml_Note",
    ],
    allowedRelations: ["uml_rel_ControlFlow", "uml_rel_NoteLink"],
    elkAlgorithm: "layered",
  },
];

export const UML_DIAGRAM_TYPE_MAP = new Map(UML_DIAGRAM_TYPES.map((t) => [t.type, t]));

export function getUmlDiagramTypeConfig(type: string): UmlDiagramTypeConfig | undefined {
  return UML_DIAGRAM_TYPE_MAP.get(type as UmlDiagramType);
}
