export interface UmlElementMeta {
  category: string;
  icon: string;
  defaultColor: string;
  defaultWidth: number;
  defaultHeight: number;
  nodeType: string;
}

export const UML_ELEMENT_META: Record<string, UmlElementMeta> = {
  // Class diagram
  uml_Class: {
    category: "UML:Class",
    icon: "view_in_ar",
    defaultColor: "#dbeafe",
    defaultWidth: 200,
    defaultHeight: 120,
    nodeType: "uml_class",
  },
  uml_AbstractClass: {
    category: "UML:Class",
    icon: "view_in_ar",
    defaultColor: "#dbeafe",
    defaultWidth: 200,
    defaultHeight: 120,
    nodeType: "uml_class",
  },
  uml_Interface: {
    category: "UML:Class",
    icon: "api",
    defaultColor: "#ede9fe",
    defaultWidth: 200,
    defaultHeight: 100,
    nodeType: "uml_class",
  },
  uml_DataType: {
    category: "UML:Class",
    icon: "data_object",
    defaultColor: "#dbeafe",
    defaultWidth: 180,
    defaultHeight: 80,
    nodeType: "uml_class",
  },
  uml_Enumeration: {
    category: "UML:Class",
    icon: "list",
    defaultColor: "#dbeafe",
    defaultWidth: 180,
    defaultHeight: 100,
    nodeType: "uml_class",
  },
  uml_PrimitiveType: {
    category: "UML:Class",
    icon: "code",
    defaultColor: "#dbeafe",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  uml_Signal: {
    category: "UML:Class",
    icon: "notifications_active",
    defaultColor: "#dbeafe",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  // Component / Deployment
  uml_Component: {
    category: "UML:Component",
    icon: "widgets",
    defaultColor: "#dcfce7",
    defaultWidth: 180,
    defaultHeight: 80,
    nodeType: "uml_component",
  },
  uml_Port: {
    category: "UML:Component",
    icon: "settings_input_component",
    defaultColor: "#dcfce7",
    defaultWidth: 40,
    defaultHeight: 40,
    nodeType: "uml_default",
  },
  uml_ProvidedInterface: {
    category: "UML:Component",
    icon: "radio_button_checked",
    defaultColor: "#dcfce7",
    defaultWidth: 40,
    defaultHeight: 40,
    nodeType: "uml_default",
  },
  uml_RequiredInterface: {
    category: "UML:Component",
    icon: "radio_button_unchecked",
    defaultColor: "#dcfce7",
    defaultWidth: 40,
    defaultHeight: 40,
    nodeType: "uml_default",
  },
  uml_Artifact: {
    category: "UML:Component",
    icon: "description",
    defaultColor: "#dcfce7",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_artifact",
  },
  uml_Node: {
    category: "UML:Component",
    icon: "dns",
    defaultColor: "#dcfce7",
    defaultWidth: 200,
    defaultHeight: 100,
    nodeType: "uml_node3d",
  },
  uml_Device: {
    category: "UML:Component",
    icon: "devices",
    defaultColor: "#dcfce7",
    defaultWidth: 200,
    defaultHeight: 100,
    nodeType: "uml_node3d",
  },
  uml_ExecutionEnvironment: {
    category: "UML:Component",
    icon: "terminal",
    defaultColor: "#dcfce7",
    defaultWidth: 200,
    defaultHeight: 100,
    nodeType: "uml_node3d",
  },
  uml_DeploymentSpec: {
    category: "UML:Component",
    icon: "settings",
    defaultColor: "#dcfce7",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  // Package
  uml_Package: {
    category: "UML:Package",
    icon: "folder_open",
    defaultColor: "#fef9c3",
    defaultWidth: 200,
    defaultHeight: 120,
    nodeType: "uml_package",
  },
  uml_Model: {
    category: "UML:Package",
    icon: "schema",
    defaultColor: "#fef9c3",
    defaultWidth: 200,
    defaultHeight: 120,
    nodeType: "uml_package",
  },
  uml_Profile: {
    category: "UML:Package",
    icon: "tune",
    defaultColor: "#fef9c3",
    defaultWidth: 200,
    defaultHeight: 120,
    nodeType: "uml_package",
  },
  uml_Stereotype: {
    category: "UML:Package",
    icon: "label",
    defaultColor: "#fef9c3",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  uml_Namespace: {
    category: "UML:Package",
    icon: "space_dashboard",
    defaultColor: "#fef9c3",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  // Use Case
  uml_Actor: {
    category: "UML:UseCase",
    icon: "person",
    defaultColor: "#fce7f3",
    defaultWidth: 60,
    defaultHeight: 90,
    nodeType: "uml_actor",
  },
  uml_UseCase: {
    category: "UML:UseCase",
    icon: "circle",
    defaultColor: "#fce7f3",
    defaultWidth: 150,
    defaultHeight: 60,
    nodeType: "uml_usecase",
  },
  uml_Subject: {
    category: "UML:UseCase",
    icon: "crop_free",
    defaultColor: "#fce7f3",
    defaultWidth: 300,
    defaultHeight: 250,
    nodeType: "uml_subject",
  },
  // Activity
  uml_Activity: {
    category: "UML:Activity",
    icon: "account_tree",
    defaultColor: "#fff7ed",
    defaultWidth: 180,
    defaultHeight: 80,
    nodeType: "uml_activity",
  },
  uml_Action: {
    category: "UML:Activity",
    icon: "play_arrow",
    defaultColor: "#fff7ed",
    defaultWidth: 160,
    defaultHeight: 50,
    nodeType: "uml_action",
  },
  uml_CallBehaviorAction: {
    category: "UML:Activity",
    icon: "call_to_action",
    defaultColor: "#fff7ed",
    defaultWidth: 160,
    defaultHeight: 50,
    nodeType: "uml_action",
  },
  uml_SendSignalAction: {
    category: "UML:Activity",
    icon: "send",
    defaultColor: "#fff7ed",
    defaultWidth: 160,
    defaultHeight: 50,
    nodeType: "uml_action",
  },
  uml_AcceptEventAction: {
    category: "UML:Activity",
    icon: "inbox",
    defaultColor: "#fff7ed",
    defaultWidth: 160,
    defaultHeight: 50,
    nodeType: "uml_action",
  },
  uml_InitialNode: {
    category: "UML:Activity",
    icon: "fiber_manual_record",
    defaultColor: "#1f2937",
    defaultWidth: 24,
    defaultHeight: 24,
    nodeType: "uml_initial",
  },
  uml_ActivityFinalNode: {
    category: "UML:Activity",
    icon: "stop_circle",
    defaultColor: "#1f2937",
    defaultWidth: 30,
    defaultHeight: 30,
    nodeType: "uml_final",
  },
  uml_FlowFinalNode: {
    category: "UML:Activity",
    icon: "cancel",
    defaultColor: "#1f2937",
    defaultWidth: 30,
    defaultHeight: 30,
    nodeType: "uml_flowfinal",
  },
  uml_DecisionNode: {
    category: "UML:Activity",
    icon: "change_history",
    defaultColor: "#fff7ed",
    defaultWidth: 40,
    defaultHeight: 40,
    nodeType: "uml_decision",
  },
  uml_ForkJoinNode: {
    category: "UML:Activity",
    icon: "drag_handle",
    defaultColor: "#1f2937",
    defaultWidth: 120,
    defaultHeight: 6,
    nodeType: "uml_forkjoin",
  },
  uml_ActivityPartition: {
    category: "UML:Activity",
    icon: "view_column",
    defaultColor: "#fff7ed",
    defaultWidth: 200,
    defaultHeight: 300,
    nodeType: "uml_partition",
  },
  uml_ObjectNode: {
    category: "UML:Activity",
    icon: "data_object",
    defaultColor: "#fff7ed",
    defaultWidth: 140,
    defaultHeight: 50,
    nodeType: "uml_default",
  },
  uml_CentralBuffer: {
    category: "UML:Activity",
    icon: "storage",
    defaultColor: "#fff7ed",
    defaultWidth: 140,
    defaultHeight: 50,
    nodeType: "uml_default",
  },
  uml_DataStoreNode: {
    category: "UML:Activity",
    icon: "database",
    defaultColor: "#fff7ed",
    defaultWidth: 140,
    defaultHeight: 50,
    nodeType: "uml_default",
  },
  // State Machine
  uml_State: {
    category: "UML:StateMachine",
    icon: "crop_square",
    defaultColor: "#f3e8ff",
    defaultWidth: 160,
    defaultHeight: 70,
    nodeType: "uml_state",
  },
  uml_CompositeState: {
    category: "UML:StateMachine",
    icon: "web",
    defaultColor: "#f3e8ff",
    defaultWidth: 240,
    defaultHeight: 160,
    nodeType: "uml_state",
  },
  uml_SubmachineState: {
    category: "UML:StateMachine",
    icon: "grid_view",
    defaultColor: "#f3e8ff",
    defaultWidth: 160,
    defaultHeight: 70,
    nodeType: "uml_state",
  },
  uml_PseudostateInitial: {
    category: "UML:StateMachine",
    icon: "fiber_manual_record",
    defaultColor: "#1f2937",
    defaultWidth: 24,
    defaultHeight: 24,
    nodeType: "uml_initial",
  },
  uml_PseudostateFinal: {
    category: "UML:StateMachine",
    icon: "stop_circle",
    defaultColor: "#1f2937",
    defaultWidth: 30,
    defaultHeight: 30,
    nodeType: "uml_final",
  },
  uml_PseudostateChoice: {
    category: "UML:StateMachine",
    icon: "change_history",
    defaultColor: "#f3e8ff",
    defaultWidth: 40,
    defaultHeight: 40,
    nodeType: "uml_decision",
  },
  uml_PseudostateJunction: {
    category: "UML:StateMachine",
    icon: "merge",
    defaultColor: "#1f2937",
    defaultWidth: 20,
    defaultHeight: 20,
    nodeType: "uml_junction",
  },
  uml_PseudostateFork: {
    category: "UML:StateMachine",
    icon: "drag_handle",
    defaultColor: "#1f2937",
    defaultWidth: 120,
    defaultHeight: 6,
    nodeType: "uml_forkjoin",
  },
  uml_PseudostateJoin: {
    category: "UML:StateMachine",
    icon: "drag_handle",
    defaultColor: "#1f2937",
    defaultWidth: 120,
    defaultHeight: 6,
    nodeType: "uml_forkjoin",
  },
  uml_PseudostateShallowHistory: {
    category: "UML:StateMachine",
    icon: "history",
    defaultColor: "#f3e8ff",
    defaultWidth: 30,
    defaultHeight: 30,
    nodeType: "uml_history",
  },
  uml_PseudostateDeepHistory: {
    category: "UML:StateMachine",
    icon: "history_edu",
    defaultColor: "#f3e8ff",
    defaultWidth: 30,
    defaultHeight: 30,
    nodeType: "uml_history",
  },
  uml_PseudostateEntryPoint: {
    category: "UML:StateMachine",
    icon: "login",
    defaultColor: "#f3e8ff",
    defaultWidth: 24,
    defaultHeight: 24,
    nodeType: "uml_entryexit",
  },
  uml_PseudostateExitPoint: {
    category: "UML:StateMachine",
    icon: "logout",
    defaultColor: "#f3e8ff",
    defaultWidth: 24,
    defaultHeight: 24,
    nodeType: "uml_entryexit",
  },
  // Sequence
  uml_Lifeline: {
    category: "UML:Sequence",
    icon: "vertical_align_top",
    defaultColor: "#ecfeff",
    defaultWidth: 120,
    defaultHeight: 200,
    nodeType: "uml_lifeline",
  },
  uml_CombinedFragment: {
    category: "UML:Sequence",
    icon: "braces",
    defaultColor: "#ecfeff",
    defaultWidth: 300,
    defaultHeight: 200,
    nodeType: "uml_fragment",
  },
  uml_InteractionOperand: {
    category: "UML:Sequence",
    icon: "splitscreen",
    defaultColor: "#ecfeff",
    defaultWidth: 300,
    defaultHeight: 80,
    nodeType: "uml_default",
  },
  uml_ExecutionSpecification: {
    category: "UML:Sequence",
    icon: "play_arrow",
    defaultColor: "#ecfeff",
    defaultWidth: 20,
    defaultHeight: 60,
    nodeType: "uml_default",
  },
  // Common
  uml_Note: {
    category: "UML:Common",
    icon: "sticky_note_2",
    defaultColor: "#fef3c7",
    defaultWidth: 160,
    defaultHeight: 80,
    nodeType: "uml_note",
  },
  uml_Constraint: {
    category: "UML:Common",
    icon: "lock",
    defaultColor: "#fef3c7",
    defaultWidth: 160,
    defaultHeight: 60,
    nodeType: "uml_note",
  },
  uml_Frame: {
    category: "UML:Common",
    icon: "crop_free",
    defaultColor: "#f8fafc",
    defaultWidth: 300,
    defaultHeight: 200,
    nodeType: "uml_frame",
  },
  uml_Object: {
    category: "UML:Common",
    icon: "data_object",
    defaultColor: "#dbeafe",
    defaultWidth: 160,
    defaultHeight: 80,
    nodeType: "uml_default",
  },
};
